#
# Copyright (c) 2021 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Linting with Vale
on:
  - pull_request_target
jobs:
  vale:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Vale Linter
        uses: benoitf/vale-action@vale-action-39
        with:
          files: __onlyModified
          styles: | 
            https://github.com/redhat-documentation/vale-at-red-hat/releases/latest/download/RedHat.zip
            https://github.com/redhat-documentation/chedocs/releases/latest/download/CheDocs.zip
          config: https://raw.githubusercontent.com/redhat-documentation/vale-at-red-hat/master/.vale-for-github-action.ini
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
